# Generated by Django 2.1.7 on 2019-04-05 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_movmensalista'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quarto',
            old_name='proprietario',
            new_name='hospede',
        ),
    ]
