# Generated by Django 2.1.7 on 2019-04-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190405_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='cidade',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoa',
            name='cpf',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
