# Generated by Django 2.2 on 2019-06-14 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quarto',
            name='hospede',
        ),
    ]
