# Generated by Django 2.2 on 2019-07-23 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_remove_quarto_cor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_diaria', models.DecimalField(decimal_places=2, help_text='Valor do quarto reservado.', max_digits=5, verbose_name='valor diária')),
                ('checkin', models.DateTimeField()),
                ('checkout', models.DateTimeField(blank=True, null=True)),
                ('forma_pagto', models.CharField(choices=[('di', 'Dinheiro'), ('de', 'Débito'), ('cr', 'Crédito')], default='de', max_length=2, verbose_name='forma de pagto')),
                ('pago', models.BooleanField(default=False)),
                ('nome_cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.Pessoa', verbose_name='cliente')),
            ],
        ),
        migrations.AlterField(
            model_name='quarto',
            name='numero',
            field=models.CharField(max_length=7, verbose_name='número'),
        ),
        migrations.AlterField(
            model_name='quarto',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='observações'),
        ),
        migrations.AlterField(
            model_name='quarto',
            name='padrao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Padrao', verbose_name='padrão'),
        ),
        migrations.AlterField(
            model_name='quarto',
            name='valor_diaria',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='valor diária'),
        ),
        migrations.DeleteModel(
            name='MovRotativo',
        ),
        migrations.AddField(
            model_name='reserva',
            name='quarto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Quarto'),
        ),
    ]
