# Generated by Django 2.2 on 2019-06-14 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_remove_quarto_hospede'),
    ]

    operations = [
        migrations.AddField(
            model_name='movrotativo',
            name='forma_pagto',
            field=models.CharField(choices=[('di', 'Dinheiro'), ('de', 'Débito'), ('cr', 'Crédito')], default='de', max_length=2, verbose_name='forma de pagto'),
        ),
        migrations.AddField(
            model_name='movrotativo',
            name='nome_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.Pessoa'),
        ),
        migrations.AlterField(
            model_name='movrotativo',
            name='valor_hora',
            field=models.DecimalField(decimal_places=2, help_text='Valor do quarto reservado.', max_digits=5),
        ),
    ]
