# Generated by Django 2.2 on 2019-07-26 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_auto_20190725_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarto',
            name='numero',
            field=models.IntegerField(verbose_name='número'),
        ),
    ]
