# Generated by Django 2.2 on 2019-07-26 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_auto_20190725_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarto',
            name='valor_diaria',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='valor diária'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='quarto',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.Quarto'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='valor_diaria',
            field=models.DecimalField(decimal_places=2, help_text='Valor do quarto reservado.', max_digits=6, verbose_name='valor diária'),
        ),
    ]
