# Generated by Django 2.2 on 2019-07-26 02:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_auto_20190725_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='pre_checkout',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 26, 2, 45, 4, 411250, tzinfo=utc), verbose_name='Previsão de Saída'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reserva',
            name='checkin',
            field=models.DateTimeField(verbose_name='Entrada'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='checkout',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Saída'),
        ),
    ]
