# Generated by Django 2.2 on 2019-11-08 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_auto_20190726_1558'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ('-pk',), 'verbose_name': 'reserva', 'verbose_name_plural': 'reservas'},
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cpf',
            field=models.CharField(max_length=14),
        ),
    ]
