# Generated by Django 2.2 on 2019-11-11 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_auto_20191107_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
